In [9]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
anpc = pd.read_csv('data/anpc-2016-preprocessed.csv')

In [3]:
anpc.head()

,Unnamed: 0,Numero,Latitude,Longitude,NumeroMeiosTerrestresEnvolvidos,NumeroOperacionaisTerrestresEnvolvidos,NumeroMeiosAereosEnvolvidos,NumeroOperacionaisAereosEnvolvidos,DuracaoEvento,AnoOcorrencia,...,Distrito_LEIRIA,Distrito_LISBOA,Distrito_PORTALEGRE,Distrito_PORTO,Distrito_SANTARÉM,Distrito_SETÚBAL,Distrito_VIANA DO CASTELO,Distrito_VILA REAL,Distrito_VISEU,Distrito_ÉVORA
0,0,2016150002576,0.000040,0.998153,1.0,3.0,0.0,0.0,0.479019,2016,...,0,0,0,0,0,1,0,0,0,0
1,2,2016020002249,0.000017,0.998249,2.0,4.0,0.0,0.0,0.478863,2016,...,0,0,0,0,0,0,0,0,0,0
2,4,2016020003825,0.000015,0.998263,1.0,2.0,0.0,0.0,0.478893,2016,...,0,0,0,0,0,0,0,0,0,0
3,5,2016110048171,0.000049,0.998110,1.0,2.0,0.0,0.0,0.478919,2016,...,0,1,0,0,0,0,0,0,0,0
4,6,2016180014340,0.000099,0.998270,2.0,7.0,0.0,0.0,0.478996,2016,...,0,0,0,0,0,0,0,0,1,0

In [7]:
anpc=anpc.drop('Unnamed: 0',axis=1)
anpc=anpc.drop('Numero',axis=1)

In [10]:
anpc.head()

,Latitude,Longitude,NumeroMeiosTerrestresEnvolvidos,NumeroOperacionaisTerrestresEnvolvidos,NumeroMeiosAereosEnvolvidos,NumeroOperacionaisAereosEnvolvidos,DuracaoEvento,AnoOcorrencia,MesOcorrencia,DiaOcorrencia,HoraOcorrencia,Grouped_Acidentes,Grouped_Assistência e Prevenção,Grouped_Incêndios,Grouped_Incêndios em Bens,Grouped_Operações,Grouped_Segurança e Serviços,Distrito_AVEIRO,Distrito_BEJA,Distrito_BRAGA,Distrito_BRAGANÇA,Distrito_CASTELO BRANCO,Distrito_COIMBRA,Distrito_FARO,Distrito_GUARDA,Distrito_LEIRIA,Distrito_LISBOA,Distrito_PORTALEGRE,Distrito_PORTO,Distrito_SANTARÉM,Distrito_SETÚBAL,Distrito_VIANA DO CASTELO,Distrito_VILA REAL,Distrito_VISEU,Distrito_ÉVORA
0,0.000040,0.998153,1.0,3.0,0.0,0.0,0.479019,2016,9,1,14,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,0.000017,0.998249,2.0,4.0,0.0,0.0,0.478863,2016,1,24,18,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0.000015,0.998263,1.0,2.0,0.0,0.0,0.478893,2016,2,13,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0.000049,0.998110,1.0,2.0,0.0,0.0,0.478919,2016,3,14,19,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0.000099,0.998270,2.0,7.0,0.0,0.0,0.478996,2016,3,14,19,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0